// examples/vite-react-jotai/src/TodoApp/components/TodoApp.tsx
import type { FC } from "react";
import "../styles/style-from-todo-mvc-website.scss";
import "../styles/style-patch.scss";
import { NewTodoBlock } from "./NewTodoBlock";
import { StatusBar } from "./StatusBar";
import { TodoList } from "./TodoList";

// * ================================================================================

export const TodoApp: FC = () => {
  return (
    <div className="todoapp">
      <h1>todos</h1>
      <NewTodoBlock />
      <TodoList />
      <StatusBar />
    </div>
  );
};

// examples/vite-vue3-pinia/src/TodoApp/components/TodoApp.vue
<script setup lang="ts">
import NewTodoBlock from "./NewTodoBlock.vue";
import StatusBar from "./StatusBar.vue";
import TodoList from "./TodoList.vue";
import "../styles/style-from-todo-mvc-website.scss";
import "../styles/style-patch.scss";
</script>

<template>
  <div class="todoapp">
    <h1>todos</h1>
    <NewTodoBlock />
    <TodoList />
    <StatusBar />
  </div>
</template>
