// examples/vite-solidjs/src/TodoApp/model/model.ts
import { nanoid } from "nanoid";
import { createMemo, createRoot, createSignal } from "solid-js";

// * ---------------------------------------------------------------- types

export type FilterMode = "ALL" | "ACTIVE" | "COMPLETED";

export interface TodoItem {
  id: string;
  content: string;
  completed: boolean;
}

// * ---------------------------------------------------------------- Solidjs signals

export const model = createRoot(() => {
  const [filter, setFilter] = createSignal<FilterMode>("ALL");

  const [todos, setTodos] = createSignal<TodoItem[]>([]);

  const model = {
    // * ---------------- todo crud

    getFiltedTodos: createMemo(() =>
      filter() === "COMPLETED"
        ? todos().filter((e) => e.completed)
        : filter() === "ACTIVE"
        ? todos().filter((e) => !e.completed)
        : todos(),
    ),

    createTodo: (todoText: string) => {
      if (!todoText) return;
      setTodos((todos) => [...todos, { id: nanoid(), content: todoText, completed: false }]);
    },

    updateTodoContent: (patch: Pick<TodoItem, "id" | "content">) => {
      setTodos((todos) => todos.map((e) => (e.id === patch.id ? { ...e, content: patch.content } : e)));
    },

    changeTodoCompletedById: (id: string) => {
      setTodos((todos) => todos.map((e) => (e.id === id ? { ...e, completed: !e.completed } : e)));
    },

    deleteTodoById: (id: string) => {
      setTodos((todos) => todos.filter((e) => e.id !== id));
    },

    // * ---------------- misc

    getRemainCount: () => todos().filter((e) => !e.completed).length,
    getHasCompleted: () => todos().filter((e) => e.completed).length > 0,

    filter,
    changeVisibility: (filter: FilterMode) => {
      setFilter(filter);
    },

    // * ---------------- toggle

    getIsAllCompleted: () => todos.length !== 0 && todos().every((e) => e.completed),

    toggleAllTodos: () => {
      setTodos((todos) => {
        const nextCompleted = todos.every((e) => e.completed) ? false : true;
        return todos.map((e) => ({ ...e, completed: nextCompleted }));
      });
    },

    clearCompleted: () => {
      setTodos((todos) => todos.filter((e) => !e.completed));
    },
  };

  return model;
});

// examples/vite-svelte/src/TodoApp/model/model.svelte
<script lang="ts" context="module">
  import { nanoid } from "nanoid";
  import { writable, derived, get } from "svelte/store";
  import type { Readable } from "svelte/store";
  import type { TodoItem, FilterMode } from "./types";

  // * ---------------------------------------------------------------- svelte writable values

  export const todos = writable<TodoItem[]>([]);

  export const filter = writable<FilterMode>('ALL');

  export const completedTodos = derived(todos, ($todos) => $todos.filter((e) => e.completed));

  export const activeTodos = derived(todos, ($todos) => $todos.filter((e) => !e.completed));

  export const hasCompleted = derived(completedTodos, ($completedTodos) => $completedTodos.length > 0);

  export const remainCount = derived(activeTodos, ($activeTodos) => $activeTodos.length);

  export const filtedTodos = derived([todos, filter], () =>
    get(filter) === 'COMPLETED'
      ? get(completedTodos)
      : get(filter) === 'ACTIVE'
      ? get(activeTodos)
      : get(todos),
  ) as Readable<TodoItem[]>;

  export const isAllCompleted = derived(todos, ($todos) => $todos.length !== 0 && $todos.every((e) => e.completed));

  // * ---------------------------------------------------------------- actions

  export const createTodo = (todoText: string) => {
    if (!todoText) return;
    todos.update((todos) => [...todos, { id: nanoid(), content: todoText, completed: false }]);
  };

  export const updateTodoContent = (patch: Pick<TodoItem, "id" | "content">) => {
    todos.update((todos) => todos.map((e) => (e.id === patch.id ? { ...e, ...patch } : e)));
  };

  export const changeTodoCompletedById = (id: string) => {
    todos.update((todos) => todos.map((e) => (e.id === id ? { ...e, completed: !e.completed } : e)));
  };

  export const deleteTodoById = (id: string) => {
    todos.update((todos) => todos.filter((e) => e.id !== id));
  };

  // * ---------------- misc

  export const changeVisibility = (mode: FilterMode) => {
    filter.set(mode);
  };

  // * ---------------- toggle

  export const toggleAllTodos = () => {
    const nextCompleted = get(todos).every((e) => e.completed) ? false : true;
    todos.update((todos) => todos.map((e) => ({ ...e, completed: nextCompleted })));
  };

  export const clearCompleted = () => {
    todos.update((todos) => todos.filter((e) => !e.completed));
  };
</script>
