// examples/vite-vue3-pinia/src/TodoApp/components/StatusBar.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { computed } from "vue";
import type { FilterMode } from "../model";
import { useFilter, useTodos } from "../model";

const filterStore = useFilter();
const { filter } = storeToRefs(filterStore);
const { changeVisibility } = filterStore;

const todoStore = useTodos();
const { remainCount, hasCompleted } = storeToRefs(todoStore);
const { clearCompleted } = todoStore;

const remainText = computed(() => `${remainCount.value} ${remainCount.value === 1 ? "item" : "items"} left`);

const filterBtnList: { target: FilterMode; text: string }[] = [
  { target: "ALL", text: "All" },
  { target: "ACTIVE", text: "Active" },
  { target: "COMPLETED", text: "Completed" },
];
</script>

<template>
  <footer class="footer">
    <span class="todo-count">{{ remainText }}</span>

    <ul class="filters">
      <li v-for="{ target, text } in filterBtnList">
        <a :class="{ selected: filter === target }" @click="() => changeVisibility(target)">
          {{ text }}
        </a>
      </li>
    </ul>

    <button v-if="hasCompleted" class="clear-completed" @click="clearCompleted">Clear completed</button>
  </footer>
</template>

// examples/vite-svelte/src/TodoApp/components/StatusBar.svelte
<script lang="ts">
  import { changeVisibility, clearCompleted, filter, hasCompleted, remainCount } from "../model/model.svelte";
  import type { FilterMode } from "../model/types";

  $: remainText = `${$remainCount} ${$remainCount === 1 ? "item" : "items"} left`;

  const filterBtnList: { target: FilterMode; text: string }[] = [
    { target: "ALL", text: "All" },
    { target: "ACTIVE", text: "Active" },
    { target: "COMPLETED", text: "Completed" },
  ];
</script>

<footer class="footer">
  <span class="todo-count">{remainText}</span>

  <ul class="filters">
    {#each filterBtnList as { target, text }}
      <li>
        <!-- svelte-ignore a11y-missing-attribute -->
        <a class:selected={$filter === target} on:click={() => changeVisibility(target)}>
          {text}
        </a>
      </li>
    {/each}
  </ul>

  {#if $hasCompleted}
    <button class="clear-completed" on:click={clearCompleted}>Clear completed</button>
  {/if}
</footer>
