// examples/vite-vue3-pinia/src/TodoApp/components/TodoListItem.vue
<script setup lang="ts">
import { ref, watchEffect } from "vue";
import type { TodoItem } from "../model";
import { useTodos } from "../model";

const { deleteTodoById } = useTodos();

// * ---------------- props

const { item } = defineProps<{ item: TodoItem }>();

const { id } = item;

// * ---------------- states

const editing = ref(false);

// * ---------------- auto focus

const todoEditInputRef = ref<HTMLInputElement | null>(null);

watchEffect(() => {
  if (editing.value) {
    // * fast fix
    setTimeout(() => {
      todoEditInputRef.value?.focus();
    }, 0);
  }
});

// * ---------------- actions

const intoTextEditing = () => {
  editing.value = true;
};

const exitTextEdition = () => {
  editing.value = false;
  if (!item.content) return deleteTodoById(id);
};
</script>

<template>
  <li :class="{ editing }">
    <div class="view">
      <input class="toggle" type="checkbox" v-model="item.completed" aria-label="toggle todo" />

      <label @dblclick="intoTextEditing">{{ item.content }}</label>
      <button class="destroy" @click="() => deleteTodoById(id)" aria-label="delete todo" />
    </div>

    <input
      ref="todoEditInputRef"
      class="edit"
      v-model="item.content"
      @keydown="(e) => e.key === 'Enter' && exitTextEdition()"
      @blur="exitTextEdition"
      aria-label="edit todo"
    />
  </li>
</template>

// examples/vite-svelte/src/TodoApp/components/TodoListItem.svelte
<script lang="ts">
  import type { TodoItem } from "../model/types";
  import { changeTodoCompletedById, deleteTodoById, updateTodoContent } from "../model/model.svelte";

  // * ---------------- props

  export let item: TodoItem;
  $: ({ id, content, completed } = item);

  // * ---------------- states

  let localText: string;
  let editing: boolean;

  // * ---------------- auto focus

  let todoEditInputRef: HTMLInputElement;

  $: if (editing) {
    // * setTimeout ia a tricky fix
    setTimeout(() => {
      todoEditInputRef.focus();
    }, 0);
  }

  // * ---------------- actions

  const intoTextEditing = () => {
    editing = true;
    localText = content;
  };

  const exitTextEdition = () => {
    editing = false;
    if (!localText) return deleteTodoById(id);
    if (localText !== content) return updateTodoContent({ id, content: localText });
  };
</script>

<li class:completed class:editing>
  <div class="view">
    <input
      class="toggle"
      type="checkbox"
      checked={completed}
      on:change={() => changeTodoCompletedById(id)}
      aria-label="toggle todo"
    />
    <!-- svelte-ignore a11y-label-has-associated-control -->
    <label on:dblclick={intoTextEditing}>{content}</label>
    <button class="destroy" on:click={() => deleteTodoById(id)} aria-label="delete todo" />
  </div>

  <input
    bind:this={todoEditInputRef}
    class="edit"
    bind:value={localText}
    on:keydown={(e) => e.key === "Enter" && exitTextEdition()}
    on:blur={exitTextEdition}
    aria-label="edit todo"
  />
</li>
