// examples/vite-svelte/src/TodoApp/components/NewTodoBlock.svelte
<script lang="ts">
  import ToggleAll from "./ToggleAll.svelte";
  import { createTodo } from "../model/model.svelte";

  let newTodoInputText = "";

  const createNewTodo = (e: KeyboardEvent) => {
    if (e.key !== "Enter") return;

    createTodo(newTodoInputText);
    newTodoInputText = "";
  };
</script>

<div>
  <ToggleAll />

  <input
    class="new-todo"
    placeholder="What needs to be done"
    bind:value={newTodoInputText}
    on:keydown={createNewTodo}
  />
</div>

// examples/vite-vue3/src/TodoApp/components/NewTodoBlock.vue
<script setup lang="ts">
import { ref } from "vue";
import ToggleAll from "./ToggleAll.vue";
import { createTodo } from "../model";

const newTodoInputText = ref("");

const createNewTodo = (e: KeyboardEvent) => {
  if (e.key !== "Enter") return;

  createTodo(newTodoInputText.value);
  newTodoInputText.value = "";
};
</script>

<template>
  <div>
    <ToggleAll />

    <input class="new-todo" placeholder="What needs to be done" v-model="newTodoInputText" @keydown="createNewTodo" />
  </div>
</template>
