// examples/vite-preact-signal-optimized/src/TodoApp/components/StatusBar.tsx
import clsx from "clsx";
import type { FunctionalComponent as FC } from "preact";
import { changeVisibilityFilter, clearCompleted, filter, FilterMode, hasCompleted, remainCount } from "../model";

// * ================================================================================

// * ---------------------------------------------------------------- StatusBar

export const StatusBar: FC = () => {
  const remainText = `${remainCount.value} ${remainCount.value === 1 ? "item" : "items"} left`;

  return (
    <footer className="footer">
      <span className="todo-count">{remainText}</span>

      <ul className="filters">
        <FilterButton target="ALL" text="All" />
        <FilterButton target="ACTIVE" text="Active" />
        <FilterButton target="COMPLETED" text="Completed" />
      </ul>

      {hasCompleted.value && (
        <button className="clear-completed" onClick={clearCompleted}>
          Clear Completed
        </button>
      )}
    </footer>
  );
};

// * ---------------------------------------------------------------- FilterButton

const FilterButton: FC<{ target: FilterMode; text: string }> = ({ target, text }) => {
  return (
    <li>
      <a className={clsx({ selected: filter.value === target })} onClick={() => changeVisibilityFilter(target)}>
        {text}
      </a>
    </li>
  );
};

// examples/vite-vue3/src/TodoApp/components/StatusBar.vue
<script setup lang="ts">
import { computed } from "vue";
import type { FilterMode } from "../model";
import { changeVisibility, clearCompleted, filter, hasCompleted, remainCount } from "../model";

const remainText = computed(() => `${remainCount.value} ${remainCount.value === 1 ? "item" : "items"} left`);

const filterBtnList: { target: FilterMode; text: string }[] = [
  { target: "ALL", text: "All" },
  { target: "ACTIVE", text: "Active" },
  { target: "COMPLETED", text: "Completed" },
];
</script>

<template>
  <footer class="footer">
    <span class="todo-count">{{ remainText }}</span>

    <ul class="filters">
      <li v-for="{ target, text } in filterBtnList">
        <a :class="{ selected: filter === target }" @click="() => changeVisibility(target)">
          {{ text }}
        </a>
      </li>
    </ul>

    <button v-if="hasCompleted" class="clear-completed" @click="clearCompleted">Clear completed</button>
  </footer>
</template>
