// examples/vite-react-rxjs/src/TodoApp/components/NewTodoBlock.tsx
import type { FC, KeyboardEvent } from "react";
import { useState } from "react";
import { createTodo, toggleAllTodos, useIsAllCompleted } from "../model";

// * ================================================================================

// * ---------------------------------------------------------------- NewTodoBlock

export const NewTodoBlock: FC = () => {
  const [newTodoInputText, setNewTodoInputText] = useState("");

  // * ---------------- actions

  const createNewTodo = (e: KeyboardEvent<HTMLInputElement>) => {
    if (e.key !== "Enter") return;

    createTodo(newTodoInputText);
    setNewTodoInputText("");
  };

  // * ---------------- render

  return (
    <div>
      <ToggleAll />

      <input
        className="new-todo"
        placeholder="What needs to be done"
        value={newTodoInputText}
        onChange={(e) => setNewTodoInputText(e.target.value)}
        onKeyDown={createNewTodo}
      />
    </div>
  );
};

// * ---------------------------------------------------------------- ToggleAll

const ToggleAll: FC = () => {
  const checked = useIsAllCompleted();

  return (
    <>
      <input id="toggle-all" className="toggle-all" type="checkbox" checked={checked} onChange={toggleAllTodos} />
      <label htmlFor="toggle-all">Mark all as complete</label>
    </>
  );
};

// examples/vite-solidjs/src/TodoApp/components/NewTodoBlock.tsx
import { Component, createSignal } from "solid-js";
import { model } from "../model/model";

// * ================================================================================

// * ---------------------------------------------------------------- NewTodoBlock

export const NewTodoBlock: Component = () => {
  const [getNewTodoInputText, setNewTodoInputText] = createSignal("");

  // * ---------------- actions

  const createNewTodo = (e: KeyboardEvent) => {
    if (e.key !== "Enter") return;

    model.createTodo(getNewTodoInputText());
    setNewTodoInputText("");
  };

  // * ---------------- render

  return (
    <div>
      <ToggleAll />

      <input
        className="new-todo"
        placeholder="What needs to be done"
        value={getNewTodoInputText()}
        onInput={(e) => setNewTodoInputText((e.target as HTMLInputElement).value)}
        onKeyDown={createNewTodo}
      />
    </div>
  );
};

// * ---------------------------------------------------------------- ToggleAll

const ToggleAll: Component = () => {
  return (
    <>
      <input
        id="toggle-all"
        className="toggle-all"
        type="checkbox"
        checked={model.getIsAllCompleted()}
        onChange={model.toggleAllTodos}
      />
      <label htmlFor="toggle-all">Mark all as complete</label>
    </>
  );
};
