// examples/vite-solidjs/src/TodoApp/components/StatusBar.tsx
import { Component } from "solid-js";
import type { FilterMode } from "../model";
import { model } from "../model";

// * ================================================================================

// * ---------------------------------------------------------------- StatusBar

export const StatusBar: Component = () => {
  const remainText = () => {
    const remainCount = model.getRemainCount();
    return `${remainCount} ${remainCount === 1 ? "item" : "items"} left`;
  };

  return (
    <footer className="footer">
      <span className="todo-count">{remainText()}</span>

      <ul className="filters">
        <FilterButton target="ALL" text="All" />
        <FilterButton target="ACTIVE" text="Active" />
        <FilterButton target="COMPLETED" text="Completed" />
      </ul>

      {model.getHasCompleted() && (
        <button className="clear-completed" onClick={model.clearCompleted}>
          Clear Completed
        </button>
      )}
    </footer>
  );
};

// * ---------------------------------------------------------------- FilterButton

const FilterButton: Component<{ target: FilterMode; text: string }> = ({ target, text }) => {
  return (
    <li>
      <a classList={{ selected: model.filter() === target }} onClick={() => model.changeVisibility(target)}>
        {text}
      </a>
    </li>
  );
};

// examples/vite-react-context-immer/src/TodoApp/components/StatusBar.tsx
import clsx from "clsx";
import type { FC } from "react";
import type { FilterMode } from "../model/model";
import { useTodoModel } from "../model/model";

// * ================================================================================

// * ---------------------------------------------------------------- StatusBar

export const StatusBar: FC = () => {
  const model = useTodoModel();
  const remainCount = model.getRemainCount();
  const hasCompleted = model.getHasCompleted();
  const clearCompleted = model.clearCompleted;
  const remainText = `${remainCount} ${remainCount === 1 ? "item" : "items"} left`;

  return (
    <footer className="footer">
      <span className="todo-count">{remainText}</span>

      <ul className="filters">
        <FilterButton target="ALL" text="All" />
        <FilterButton target="ACTIVE" text="Active" />
        <FilterButton target="COMPLETED" text="Completed" />
      </ul>

      {hasCompleted && (
        <button className="clear-completed" onClick={clearCompleted}>
          Clear Completed
        </button>
      )}
    </footer>
  );
};

// * ---------------------------------------------------------------- FilterButton

const FilterButton: FC<{ target: FilterMode; text: string }> = ({ target, text }) => {
  const model = useTodoModel();
  const filter = model.getFilterValue();
  const changeVisibility = model.changeVisibility;

  return (
    <li>
      <a className={clsx({ selected: filter === target })} onClick={() => changeVisibility(target)}>
        {text}
      </a>
    </li>
  );
};
