// examples/vite-solidjs/src/TodoApp/components/TodoList.tsx
import { Component, createEffect, createSignal } from "solid-js";
import { model, TodoItem } from "../model/model";
import clsx from "clsx";

// * ================================================================================

// * ---------------------------------------------------------------- TodoList

export const TodoList: Component = () => {
  return (
    <ul className="todo-list">
      {model.getDisplayTodos().map((item) => (
        <TodoListItem item={item} />
      ))}
    </ul>
  );
};

// * ---------------------------------------------------------------- TodoListItem

const TodoListItem: Component<{ item: TodoItem }> = ({ item }) => {
  const { id, content, completed } = item;

  const [getLocalText, setLocalText] = createSignal("");
  const [isEditing, setEditing] = createSignal(false);

  // * ---------------- input auto focus effect

  let todoEditInputRef: HTMLInputElement;

  createEffect(() => {
    isEditing() && todoEditInputRef?.focus();
  });

  // * ---------------- action

  const intoTextEditing = () => {
    setEditing(true);
    setLocalText(content);
  };

  const exitTextEdition = () => {
    setEditing(false);
    if (getLocalText() !== content) model.updateTodoContent({ id, content: getLocalText() });
  };

  // * ---------------- render

  return (
    <li classList={{ completed, editing: isEditing() }}>
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={completed}
          onChange={() => model.changeTodoCompletedById(id)}
          aria-label="toggle todo"
        />
        <label onDblClick={intoTextEditing}>{content}</label>
        <button className="destroy" onClick={() => model.deleteTodoById(id)} aria-label="delete todo" />
      </div>

      <input
        // @ts-ignore
        ref={todoEditInputRef}
        className="edit"
        value={getLocalText()}
        onChange={(e) => setLocalText((e.target as HTMLInputElement).value)}
        onKeyDown={(e) => e.key === "Enter" && exitTextEdition()}
        onBlur={exitTextEdition}
        aria-label="edit todo"
      />
    </li>
  );
};

// examples/vite-preact-context/src/TodoApp/components/TodoList.tsx
import clsx from "clsx";
import type { FunctionalComponent as FC } from "preact";
import { useEffect, useRef, useState } from "preact/compat";
import type { TodoItem } from "../model/model";
import { useTodoModel } from "../model/model";

// * ================================================================================

// * ---------------------------------------------------------------- TodoList

export const TodoList: FC = () => {
  const model = useTodoModel();
  const todos = model.getDisplayTodos();

  return (
    <ul className="todo-list">
      {todos.map((item) => (
        <TodoListItem key={item.id} item={item} />
      ))}
    </ul>
  );
};

// * ---------------------------------------------------------------- TodoListItem

const TodoListItem: FC<{ item: TodoItem }> = ({ item }) => {
  const model = useTodoModel();

  const { id, content, completed } = item;

  const [localText, setLocalText] = useState("");
  const [editing, setEditing] = useState(false);

  // * ---------------- input auto focus effect

  const todoEditInputRef = useRef<HTMLInputElement>(null);
  useEffect(() => todoEditInputRef.current?.focus(), [editing]);

  // * ---------------- action

  const updateTodoContent = model.updateTodoContent;
  const changeTodoCompletedById = model.changeTodoCompletedById;
  const deleteTodoById = model.deleteTodoById;

  const intoTextEditing = () => {
    setEditing(true);
    setLocalText(content);
  };

  const exitTextEdition = () => {
    setEditing(false);
    if (localText !== content) updateTodoContent({ id, content: localText });
  };

  // * ---------------- render

  return (
    <li className={clsx({ completed: completed, editing })}>
      <div className="view">
        <input
          className="toggle"
          type="checkbox"
          checked={completed}
          onChange={() => changeTodoCompletedById(id)}
          aria-label="toggle todo"
        />
        <label onDblClick={intoTextEditing}>{content}</label>
        <button className="destroy" onClick={() => deleteTodoById(id)} aria-label="delete todo" />
      </div>

      <input
        ref={todoEditInputRef}
        className="edit"
        value={localText}
        onChange={(e) => setLocalText((e.target as HTMLInputElement).value)}
        onKeyDown={(e) => e.key === "Enter" && exitTextEdition()}
        onBlur={exitTextEdition}
        aria-label="edit todo"
      />
    </li>
  );
};
